# ruff: noqa: N815 - camelCase fields match frontend API contract
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field


class ModelConfig(BaseModel):
    id: str
    name: str
    provider: Literal["anthropic", "openai"]
    modelName: str
    apiKey: str = ""
    baseUrl: str
    maxContextTokens: int
    maxCompletionTokens: int
    maxConcurrent: int = 5
    temperature: float = 1.0
    topP: float = 1.0
    thinking: bool = True

    @property
    def core_dict(self) -> dict:
        """转换为 Model.from_config_dict() 所需格式"""
        return {
            "provider": self.provider,
            "model": self.modelName,
            "api_key": self.apiKey,
            "base_url": self.baseUrl,
            "max_completion_tokens": self.maxCompletionTokens,
            "max_context_tokens": self.maxContextTokens,
            "max_concurrent": self.maxConcurrent,
            "temperature": self.temperature,
            "top_p": self.topP,
            "thinking": self.thinking,
        }


class ToolConfig(BaseModel):
    """Blueprint (template) for a tool.

    Per the unified-id design:
    - id: UUID, the machine identity (template_id). Persisted in disk json.
      For builtin tools, derived via uuid5 from short_name. For MCP tools,
      derived from `(mcpServerId, rawName)` as a stable uuid5 hash.
    - name: display name. For builtin tools, the shortName (e.g. 'read').
      For MCP tools, the rawName on the MCP server.
    - source: tool origin (built_in | hook | mcp | team).
    - mcpServerId: only set for MCP tools; references MCPServerConfig.id.
    """
    id: str
    name: str
    source: Literal["built_in", "hook", "mcp", "team"] = "built_in"
    description: str = ""
    mcpServerId: str | None = None


class SkillConfig(BaseModel):
    id: str
    name: str
    description: str = ""
    path: str


class MCPServerConfig(BaseModel):
    id: str
    name: str
    command: str
    args: list[str] = Field(default_factory=list)
    env: dict[str, str] = Field(default_factory=dict)
    tools: list[ToolConfig] = Field(default_factory=list)


class PromptConfig(BaseModel):
    id: str
    name: str
    content: str
    group: str = ""


class MessageItem(BaseModel):
    id: str
    role: Literal["user", "assistant", "system"]
    content: str
    timestamp: int


class AgentSummary(BaseModel):
    id: str
    name: str
    type: Literal["single", "team"] = "single"
    modelId: str
    state: str = "ready"
    hookEnabled: bool = False


class TimerConfig(BaseModel):
    name: str
    type: str = "interval"  # "interval" or "at"
    seconds: float = 0.0  # for interval type
    time: str = ""  # for at type, format "HH:MM" or "HH:MM:SS"
    hint: str = ""
    enabled: bool = True


class AgentConfig(BaseModel):
    """Frontend-facing agent configuration payload.

    Per the unified-id design:
    - id: UUID, machine identity. Generated by backend on POST; frontend
      never sets it. All URL paths and storage addresses use id.
    - name: display name, may be duplicated across agents.

    Logical groups:
      - Basic:    name, modelId, systemPrompt, workingDir
      - Tools:    toolIds, skillIds, toolPolicy
      - Hooks:    hookNames, hookConfig

    Notes:
      - toolPolicy is the canonical storage for per-agent tool config. cwd
        lives inside toolPolicy (not split out). The frontend mirrors cwd
        in the top-level workingDir field for UI ergonomics; backend keeps
        them in sync on read/write.
      - workingDir and toolPolicy.cwd are kept consistent: on read,
        workingDir is derived from toolPolicy.cwd; on write, if workingDir
        is provided and toolPolicy.cwd is empty, workingDir seeds cwd.
      - toolPolicy fields are read/written through; each tool creator
        extracts the fields it needs.
      - hookConfig is a single shared dict covering all hooks; each hook
        creator picks the fields relevant to it. Hidden fields (e.g. submodel,
        embedding_model object instances) are resolved backend-side from
        submodelId.
      - hookNames is the list of enabled built-in hooks.
      - toolIds and skillIds store ToolConfig.id and SkillConfig.id
        (UUIDs).
    """

    model_config = ConfigDict(extra="ignore")

    id: str = ""
    name: str
    modelId: str
    systemPrompt: str = ""
    workingDir: str = ""
    # baseDir is auto-generated by backend (DATA_DIR/agents/{id}/).
    # Frontend never sets it on POST; backend returns it on GET so the
    # UI can render the agent's basedir file tree.
    baseDir: str = ""
    toolIds: list[str] = Field(default_factory=list)
    skillIds: list[str] = Field(default_factory=list)
    toolPolicy: dict = Field(default_factory=dict)
    hookNames: list[str] = Field(default_factory=list)
    hookConfig: dict = Field(default_factory=dict)
    timers: list[TimerConfig] = Field(default_factory=list)
    lastSessionId: str = ""


# === Hook descriptor schema (returned by GET /api/hooks) ===

HookFieldType = Literal["string", "text", "number", "float", "boolean", "modelId"]


class HookFieldSchema(BaseModel):
    key: str
    type: HookFieldType
    label: str = ""
    default: Any = None
    description: str = ""


class HookSection(BaseModel):
    title: str
    fields: list[HookFieldSchema]


class HookDescriptor(BaseModel):
    name: str
    displayName: str
    description: str = ""
    defaultEnabled: bool = True
    fieldSections: list[HookSection] = Field(default_factory=list)


class HookListResponse(BaseModel):
    hooks: list[HookDescriptor]
    sharedSections: list[HookSection] = Field(default_factory=list)


class TeamConfig(BaseModel):
    id: str = ""
    name: str
    teamDescription: str = ""
    workingDir: str = ""
    baseDir: str = ""
    memberIds: list[str] = Field(default_factory=list)
    contacts: dict[str, dict[str, str]] = Field(default_factory=dict)
    started: bool = False


class CreateTeamRequest(BaseModel):
    """Frontend-facing team creation payload.

    Separates team-level config from member agent configs, so the frontend
    no longer needs to send a bloated Agent object with empty placeholder
    fields for the team itself.

    workingDir is the shared working directory for all member agents.
    """
    name: str
    teamDescription: str = ""
    workingDir: str = ""
    members: list[AgentConfig] = Field(default_factory=list)
    contacts: dict[str, dict[str, str]] = Field(default_factory=dict)


class FileNode(BaseModel):
    name: str
    path: str
    type: Literal["file", "directory"]
    children: list["FileNode"] = Field(default_factory=list)
    size: int | None = None
    extension: str | None = None
    modifiedAt: int | None = None


class UIState(BaseModel):
    currentTab: Literal["agent", "team"] = "agent"
    currentAgentId: str | None = None
    currentTeamId: str | None = None
    settingsOpen: bool = False
    settingsTab: str = "models"
    workingDirPath: str = ""


class ChatMessage(BaseModel):
    type: Literal["user_message", "system_event"]
    content: str


class ModelTestRequest(BaseModel):
    prompt: str = "Hello, respond with a short greeting."


class SessionForkRequest(BaseModel):
    turnIndex: int
    targetAgentId: str | None = None
