export interface Model {
  id: string;
  name: string;
  provider: "anthropic" | "openai";
  modelName: string;
  apiKey: string;
  baseUrl: string;
  maxContextTokens: number;
  maxCompletionTokens: number;
  temperature?: number;
  topP?: number;
  thinking?: boolean;
}

// Tool 同时表示内置工具和 MCP 工具（unified-id 设计）：
// - id: 唯一 template_id（UUID）。前端用作 React key 和 agent.toolNames 的存储值
// - name: builtin 为短名（如 'bash'），MCP 工具为 rawName
// - source: 工具来源 ("built_in" | "mcp" | "hook" | "team")
// - mcpServerId: 仅 MCP 工具设置，引用 MCPServerConfig.id
// - mcpServerName: 仅 UI 分组用，引用 MCPServerConfig.name（不用于路由）
export interface Tool {
  id: string;
  name: string;
  source: "built_in" | "hook" | "mcp" | "team";
  description: string;
  inputSchema: {
    type: string;
    properties?: Record<
      string, { type: string; description?: string; default?: unknown }
    >;
    required?: string[];
  };
  mcpServerId?: string;
  mcpServerName?: string;  // legacy: UI grouping only
}

export interface Skill {
  id: string;
  name: string;
  description: string;
  path: string;
  body: string;
  metadata: {
    license?: string;
    compatibility?: string;
    version?: string;
    allowedTools?: string[];
    metadata?: Record<string, unknown>;
  };
}

export interface MCPServer {
  id: string;
  name: string;
  command: string;
  args: string[];
  env: Record<string, string>;
  tools: Tool[];
}

export interface Prompt {
  id: string;
  name: string;
  content: string;
  description?: string;
}

export interface Message {
  id: string;
  role: "user" | "assistant" | "system";
  content: string;
  timestamp: number;
  sourceAgent?: string;
  chunkType?: "text" | "thinking" | "tool_use" | "tool_result" | "error";
  thinking?: string;
  toolName?: string;
  toolInput?: Record<string, unknown>;
  toolResult?: string;
  messageId?: string;
}

export interface SessionInfo {
  id: string;
  timestamp: string;
  turnCount: number;
  isActive: boolean;
}

// ToolPolicy: shared config for all built-in tools. cwd is NOT here —
// backend derives it from the top-level workingDir. All field names are
// camelCase to match the API contract.
export interface ToolPolicy {
  maxReadSize?: number;
  maxReadLines?: number;
  maxWriteSize?: number;
  writeCreateDirectories?: boolean;
  bashMaxOutputLines?: number;
  bashDefaultTimeout?: number;
}

export interface Agent {
  // id: 唯一 UUID 标识（unified-id 设计）。后端生成，前端只读。
  // URL 路径、agent.toolNames / skillNames 都基于 id 路由。
  id: string;
  name: string;
  type: "single" | "team";
  // basePath is auto-generated by backend; frontend reads it but never sends.
  basePath: string;
  // workingDir is the user-facing working directory (top-level on the API).
  workingDir: string;
  modelId: string;
  systemPrompt: string;
  // toolNames 存的是 Tool.id（UUID）列表
  toolNames: string[];
  // skillNames 存的是 Skill.id（UUID）列表
  skillNames: string[];
  hookNames: string[];
  // Shared hook config (one big dict covering all hooks). Includes
  // submodelId for selecting the memory subsystem's model.
  hookConfig: Record<string, unknown>;
  toolPolicy: ToolPolicy;
  teamDescription?: string;
  members?: Agent[];
  baseDir?: string;
  contacts?: Record<string, Record<string, string>>;
  teamPrompt?: string;
  messages: Message[];
  state: "ready" | "waiting" | "running" | "error";
  sessions: SessionInfo[];
  currentSessionId: string;
}

// === Hook descriptor (returned by GET /api/hooks) ===

export type HookFieldType = "string" | "text" | "number" | "float" | "boolean" | "modelId";

export interface HookFieldSchema {
  key: string;
  type: HookFieldType;
  label: string;
  default: unknown;
  description: string;
}

export interface HookSection {
  title: string;
  fields: HookFieldSchema[];
}

export interface HookDescriptor {
  name: string;
  displayName: string;
  description: string;
  defaultEnabled: boolean;
  fieldSections: HookSection[];
}

export interface HookListResponse {
  hooks: HookDescriptor[];
  sharedSections: HookSection[];
}

export interface FileNode {
  name: string;
  path: string;
  type: "file" | "directory";
  children?: FileNode[];
  size?: number;
  extension?: string;
  modifiedAt?: number;
}

export type SettingsTab = "models" | "skills" | "mcps" | "prompts";
